const Env = {
  SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL,
  SUPABASE_PUBLIC_KEY: process.env.EXPO_PUBLIC_SUPABASE_PUBLIC_KEY,
  SUPABASE_PRIVATE_KEY: process.env.EXPO_PUBLIC_SUPABASE_PRIVATE_KEY,
};

export default Env;
